// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "expandable-card": {
      name: "expandable-card",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/expandable-card.tsx"],
      component: React.lazy(() => import("@/components/prismui/expandable-card.tsx")),
      source: "",
      category: "components",
      subcategory: "display",
      chunks: []
    },
    "chat-input": {
      name: "chat-input",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/chat-input.tsx"],
      component: React.lazy(() => import("@/components/prismui/chat-input.tsx")),
      source: "",
      category: "components",
      subcategory: "form",
      chunks: []
    },
  },
}
